name: Build Project

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BUILD_PATH: '${{github.workspace}}/artifacts'

on:
  push:
    branches:
      - keyed-service-support
    tags:
      - 'v*'
  pull_request:
    branches:
      - keyed-service-support
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Calculate Version
      run: |
        dotnet tool update -g minver-cli
        echo "BUILD_VERSION=$(minver -v e -t v)" >> $GITHUB_ENV

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Solution
      run: 'dotnet build --no-restore --configuration Release -p:Version="${{env.BUILD_VERSION}}" -p:InformationalVersion="${{env.BUILD_VERSION}}+${{github.sha}}"'

    - name: Run Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Create Packages
      if: success() && github.event_name != 'pull_request'
      run: 'nuget pack Injectio.nuspec -Version "${{env.BUILD_VERSION}}" -OutputDirectory "${{env.BUILD_PATH}}" -p Configuration=Release'

    - name: Upload Packages
      if: success() && github.event_name != 'pull_request'
      uses: actions/upload-artifact@v3
      with:
        name: packages
        path: '${{env.BUILD_PATH}}'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/keyed-service-support' || startsWith(github.ref, 'refs/tags/v'))

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: packages

    - name: Publish Packages GitHub
      run: |
        for package in $(find -name "*.nupkg"); do
          echo "${0##*/}": Pushing $package...
          dotnet nuget push $package --source https://nuget.pkg.github.com/noobiemir/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        done
